### PR TITLE
Changes to update package sources and AMIs

### PR DESCRIPTION
**Pull request by martindanielj**
Made changes to ec2.sh to update AMIs and log location.  

Changes were made to aws/ec2_bootstrap.sh to change:

- log location
- package sources
- github repo

### CODE REVIEW

**Comment by rjurney** [comment]
It says closed. Should I merge it?

**Comment by martindanielj** [comment]
I was trying to merge to my master branch - not yours. Apologies.

**Comment by rjurney** [comment]
Are these fixes we want because they fix things broken?

**Comment by martindanielj** [comment]
I had a couple issues with some of the links but what I did here was
actually redoing my infrastructure with an ubuntu 18 ami and new versions
of everything. Most of it has not been tested yet on an AWS stack yet.

**Pull request closed without merging**
